[package]
name = "simple_web_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5"
diesel = {version = "1.4", features = ["sqlite"]}
dotenv = "0.15"
tera = "1"
rand = "0.8"
openssl = "0.10"
