[package]
name = "simple_web_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = {version = "0.5", features = ["http2"]}
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tower = "0.4"

tokio-util = { version = "0.7.3", features = ["io"]}

diesel = {version = "1.4", features = ["sqlite", "r2d2"]}
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"
tera = "1"
rand = "0.8"
openssl = "0.10"
